/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

(* keep =  1  *)
(* top =  1  *)
(* src = "rtl/cpu_core.sv:1.1-186.10" *)
module cpu_core(clk, reset);
  (* src = "rtl/cpu_core.sv:2.17-2.20" *)
  input clk;
  wire clk;
  (* hdlname = "dmem_inst clk" *)
  (* src = "rtl/data_memory.sv:3.17-3.20" *)
  (* unused_bits = "0" *)
  wire \dmem_inst.clk ;
  (* hdlname = "pc_inst clk" *)
  (* src = "rtl/pc.sv:2.17-2.20" *)
  (* unused_bits = "0" *)
  wire \pc_inst.clk ;
  (* hdlname = "pc_inst reset" *)
  (* src = "rtl/pc.sv:3.17-3.22" *)
  (* unused_bits = "0" *)
  wire \pc_inst.reset ;
  (* src = "rtl/cpu_core.sv:3.17-3.22" *)
  input reset;
  wire reset;
  (* hdlname = "rf_inst clk" *)
  (* src = "rtl/register_file.sv:2.17-2.20" *)
  (* unused_bits = "0" *)
  wire \rf_inst.clk ;
  assign \dmem_inst.clk  = clk;
  assign \pc_inst.clk  = clk;
  assign \pc_inst.reset  = reset;
  assign \rf_inst.clk  = clk;
endmodule
